# Generated by Django 4.1.3 on 2023-05-24 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prod_id", models.CharField(default=1051923, max_length=14)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("item_type", models.CharField(max_length=7)),
                ("item_unit", models.CharField(max_length=15)),
                ("item_name", models.CharField(max_length=100)),
                ("item_slug", models.CharField(blank=True, max_length=100)),
                ("item_description", models.CharField(max_length=150)),
                (
                    "item_parchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "item_sale_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
    ]
